### PR TITLE
Pass env variables from vstest to debugger

### LINKED ISSUE #5131: Debug Test can't receive `DYLD_LIBRARY_PATH` variable in macOS.
## Issue Description ##

I set the `DYLD_LIBRARY_PATH` in the zshrc, then run dotnet test print the env variable value. but when I use debug Test , It can not get the variable value.

I record a video:
1. I have not set the `CUSTOM_VAR` in the zshrc, then run the dotnet test, It's can print the `DYLD_LIBRARY_PATH` variable value.
2. I set the `CUSTOM_VAR` in the zshrc, then restart the vscode and click `Debut Test`, Now in terminal we can see the `CUSTOM_VAR` variable, but `DYLD_LIBRARY_PATH ` is null.
3. use dotnet test, I can get both environment variable value.

https://user-images.githubusercontent.com/26156999/160542063-cf23a55a-9de8-4837-ab27-434286b7c298.mov

## Steps to Reproduce ##

1. write the `export DYLD_LIBRARY_PATH="xxx"` in the `~/.zshrc`
4. restart the viscose
5. click the debug test with code:
```csharp
   [Fact]
    public void TestGETENV()
    {
        // var env = System.Environment.GetEnvironmentVariables();
        // foreach (var k in env.Keys)
        // {
        //     System.Console.WriteLine(k + ": " + env[k]);
        // }
        System.Console.WriteLine("Get DYLD_LIBRARY_PATH : " + System.Environment.GetEnvironmentVariable("DYLD_LIBRARY_PATH"));
        System.Console.WriteLine("Get CUSTOM_VAR : " + System.Environment.GetEnvironmentVariable("CUSTOM_VAR"));
    }
```

## Expected Behavior ##

will print the `Get DYLD_LIBRARY_PATH : xxx`

## Actual Behavior ##

`Get DYLD_LIBRARY_PATH : `

### OmniSharp log ###
<details>Post the output from Output-->
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"TestSession.Connected","Payload":null}
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"ProtocolVersion","Payload":1}
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session ended.
</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.65.2
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-comments|aaron-bond|2.1.0|
|change-case|wmaurer|1.0.0|
|clang-format|xaver|1.9.0|
|codestream|CodeStream|12.13.0|
|copilot|GitHub|1.9.5350|
|csharp|ms-dotnettools|1.24.1|
|doxdocgen|cschlosser|1.4.0|
|file-icons|file-icons|1.0.29|
|gitlens|eamodio|12.0.5|
|hexeditor|ms-vscode|1.9.5|
|icons-carbon|antfu|0.2.4|
|increment-selection|albymor|0.2.0|
|material-theme|zhuangtongfa|3.13.20|
|remote-ssh|ms-vscode-remote|0.76.1|
|remote-ssh-edit|ms-vscode-remote|0.76.1|
|test-adapter-converter|ms-vscode|0.1.5|
|todo-tree|Gruntfuggly|0.0.215|
|vscode-clangd|llvm-vs-code-extensions|0.1.15|
|vscode-lldb|vadimcn|1.7.0|
|vscode-test-explorer|hbenl|2.21.1|
|vscode-wakatime|WakaTime|18.0.8|
|vscode-yaml|redhat|1.5.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.17|;

</details>

### PR DESCRIPTION
**Pull request by nohwnd**
Fix #5131 

Passes on env variables from the test request to the debugger.

### CODE REVIEW

File: src/features/dotnetTest.ts [hunk 1]
```diff
@@ -333,7 +333,8 @@ export default class TestManager extends AbstractProvider {
             debuggerEventsPipeName: debuggerEventsPipeName,
             program: program,
             args: args,
-            cwd: cwd
+            cwd: cwd,
+            env: environmentVariables,
```
Comment (nohwnd) [inline src/features/dotnetTest.ts:337]: @gregg-miskelly  please review, I am not sure if I need to do additional merging on the existing `result` which is a collection of debugger config, over which the new configuration is spread. Can it have env on it already?

Comment (gregg-miskelly) [reply src/features/dotnetTest.ts:337]: No, you shouldn't need to. It is not valid according to the schema ([set here](https://github.com/OmniSharp/omnisharp-vscode/blob/1d71dab8cbd0dfb653fbdb8567dcbf4e3be102d8/package.json#L595)).

**Review by gregg-miskelly — APPROVED** [review]
