### PR TITLE
Use new `/codestructure` endpoint from OmniSharp

### LINKED ISSUE #2132: Code lens never loads
## Environment data
```
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
VS Code version:
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64

C# Extension version:
1.14.0

## Steps to reproduce
Unsure,
I have a machine with vs code and the c# extension running windows 10 professional same environment otherwise and code lens loads.
Project builds and restores correctly otherwise.

Omnisharp logs contains no errors or warnings 

## Expected  behavior
code lens should load 

## Actual behavior
code lens never loads making it extremely difficult to debug tests.

### LINKED ISSUE #2192: executeDocumentSymbolProvider
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version: 1.22.2
C# Extension version: 1.14.0

## Steps to reproduce
When creating an extension, omnisharp-vscode doesn't seem to produce a symbol array. (Where as a lot of other extensions do support this.) despite the fact that omnisharp-vscode does have a DocumentSymbolProvider

```TypeScript
 var active = vscode.window.activeTextEditor.document.uri;
 vscode.commands.executeCommand('vscode.executeDocumentSymbolProvider', active)
```

## Expected  behavior
Getting an array back from the executeDocumentSymbolProvider of the C# document that's open and in focus.

## Actual behavior

Empty array.

### LINKED ISSUE #2307: Namespace not provided from `documentSymbolProvider`
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
VS Code version: 1.23.1
C# Extension version: 1.15.2

## Steps to reproduce

Given the code generated from `dotnet new console -o myApp`

1. Open `Program.cs`
2. Open Document Symbol Provider

## Expected  behavior

See the `namespace`  and `using` entries in the list of provided symbols

## Actual behavior

None of them is present

------

From what I could've get as info from the provider it seems that they are not being reported by the server

### LINKED ISSUE #2329: Flat symbol list C#
https://github.com/patrys/vscode-code-outline/issues/47

the symbol tree outline shows flat for c#

> I guess C# reports symbols differently to most other languages. Unfortunately previous approach broke in many more languages so I think the best solution would be to file a bug against the C# symbol provider and have it report symbol ranges containing the entire class/method definition instead of just their names/signatures.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #2132
Fixes #2192
Fixes #2307
Fixes #2329

This change takes advantage of the new `/codestructure` endpoint in two providers: the `CodeLensProvider` and the `DocumentSymbolProvider`.

* `CodeLensProvider` has been overhauled. The logic to compute the references and test code lenses has been unified. In addition, there was an issue with using `await` in a loop within the `provideCodeLenses` method that could cause the method to return to VS Code before the code lenses were actually added to the result array.
* The `DocumentSymbolProvider` gets a lot of benefit from this change because the `/codestructure` endpoint includes all types and members, and not just a strange handful:

    image

### CODE REVIEW

File: src/features/documentSymbolProvider.ts [hunk 1]
```diff
@@ -4,20 +4,89 @@
...
+        }
+
+        return [];
+    }
+}
+
+function createSymbols(elements: Structure.CodeElement[], fileName: string): vscode.SymbolInformation[] {
+    let results: vscode.SymbolInformation[] = [];
+
+    function walkCodeElements(elements: Structure.CodeElement[], parentElementName?: string): void {
```
Comment (rchande) [inline src/features/documentSymbolProvider.ts]: Wonder if there's a helper we can extract...

File: src/features/codeLensProvider.ts [hunk 2]
```diff
@@ -6,171 +6,276 @@
...
-    private static filteredSymbolNames: { [name: string]: boolean } = {
-        'Equals': true,
-        'Finalize': true,
-        'GetHashCode': true,
-        'ToString': true
-    };
-
-    async provideCodeLenses(document: vscode.TextDocument, token: vscode.CancellationToken) {
-        let options = this.optionProvider.GetLatestOptions();
+    async provideCodeLenses(document: vscode.TextDocument, token: vscode.CancellationToken): Promise<vscode.CodeLens[]> {
```
Comment (rchande) [inline src/features/codeLensProvider.ts]: I'm sure there are zero tests for this, right 😄

Comment (DustinCampbell) [reply src/features/codeLensProvider.ts]: yes, I was planning to add some.

File: src/features/documentSymbolProvider.ts (hunk 1 above)
Comment (DustinCampbell) [reply src/features/documentSymbolProvider.ts]: Yeah, I'll do that.

File: src/features/codeLensProvider.ts (hunk 2 above)
Comment (DustinCampbell) [reply src/features/codeLensProvider.ts]: Added integration tests for both DocumentSymbolProvider and CodeLensProvider

File: src/features/codeLensProvider.ts [hunk 3]
```diff
@@ -6,171 +6,268 @@
...
-        if (codeLens instanceof OmniSharpCodeLens) {
-
-            let req = <protocol.FindUsagesRequest>{
-                FileName: codeLens.fileName,
-                Line: codeLens.range.start.line + 1,
-                Column: codeLens.range.start.character + 1,
-                OnlyThisFile: false,
-                ExcludeDefinition: true
+    private async resolveTestCodeLens(codeLens: TestCodeLens, singularTitle: string, singularCommandName: string, pluralTitle: string, pluralCommandName: string): Promise<vscode.CodeLens> {
+        if (codeLens.testMethodNames.length === 1) {
```
Comment (akshita31) [inline src/features/codeLensProvider.ts]: Does this mean that if we have a class which has a single test in it , we will display - "Run Test" instead of "Run All Tests" ?

Comment (DustinCampbell) [reply src/features/codeLensProvider.ts]: Yes. That was a mistake. Will fix.

**Comment by DustinCampbell** [comment]
Sigh. I don't know why this is failing in CI. It all passes locally on my Mac. I'll have to look at this when I get back from vacation in July, unless somebody else has time to take a look.

**Comment by akshita31** [comment]
@DustinCampbell I forked your branch and tried to run the integration tests, but the tests are failing on Windows. I tried on two separate machines just to be sure.

CodeLensProvider: single csproj at root of workspace
base.js:240
       Returns all code lenses:
      AssertionError: expected 8 to equal 2
      + expected - actual
      -8
      +2

File: src/features/codeLensProvider.ts [hunk 4]
```diff
@@ -6,171 +6,271 @@
...
-                };
+    return results;
+}
+
+function createCodeLensesForElement(element: Structure.CodeElement, fileName: string, options: Options): vscode.CodeLens[] {
+    let results: vscode.CodeLens[] = [];
 
-                return codeLens;
-            });
+    if (options.showReferencesCodeLens && isValidElementForReferencesCodeLens(element)) {
```
Comment (akshita31) [inline src/features/codeLensProvider.ts]: Is it possible to add a test to verify that we show the codelenses  only when the appropriate option is set to true ?

**Comment by akshita31** [comment]
@DustinCampbell I have created a PR to your branch to add the name to the test code lens so that when do a Run/Debug All Tests, we can display the name of the class as well in the logs.

If you want we can put that in this PR or I could create a separate PR directly to master after your changes are merged.

Here is the effect of the change( I have highlighted the added line):
runtests

**Comment by akshita31** [comment]
@DustinCampbell Should we make changes to the `DocumentSymbolProvider` as per https://github.com/OmniSharp/omnisharp-vscode/issues/2414

File: src/features/codeLensProvider.ts (hunk 4 above)
Comment (DustinCampbell) [reply src/features/codeLensProvider.ts]: Sure. I'll give that a shot.

**Comment by DustinCampbell** [comment]
@akshita31: tests seems to be passing fine now. Did something change to fix that?

File: src/features/codeLensProvider.ts (hunk 4 above)
Comment (DustinCampbell) [reply src/features/codeLensProvider.ts]: It looks like this might be a little involved. It looks like the infrastructure is currently designed so that  _all_ integration tests run on both the 'singleCsproj' test asset and the 'slnWithCsproj' test asset. However, the only workspace with a test project is 'slnWithCsproj', so I need to write a test that specifically targets that. Since coverage for this option already didn't exist, are you OK if I merge without it and file an issue?

Comment (akshita31) [reply src/features/codeLensProvider.ts]: Yup, we can add that later.

Comment (DustinCampbell) [reply src/features/codeLensProvider.ts]: I went ahead and did it anyway. It's not amazing code, but it works. :smile:

**Comment by DustinCampbell** [comment]
@akshita31, @rchande : This PR also fixes some significant issues with integration test projects. Essentially, there were several places where the project file name was used when a project directory name was expected. This resulted with some weird `path.join`'s, e.g. `src/app/app.csproj/bin`.

**Comment by DustinCampbell** [comment]
I'll go ahead and merge since @rchande also merged the code folding work. Note that this won't work in master until it is updated with a newer OmniSharp, so folks will need to set `"omnisharp.path": "latest"`.
