### PR TITLE
Pass editor tab/indentation settings to OmniSharp

### LINKED ISSUE #834: editor.formatOnType does not respect editor.insertSpaces setting
_From @j-h-a on October 20, 2016 15:58_
- VSCode Version:
  1.6.1
- OS Version:
  OSX (10.11.6)
### Searchable description

VS Code keeps changing some lines to have spaces instead of tabs in the leading whitespace.
### Steps to Reproduce:

Use these settings:
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
    "editor.formatOnType": true,

Type some code that triggers formatOnType to activate a format change.
### Expected behaviour:

Line is formatted using tabs for leading whitespace, because of the insertSpaces setting.
### Actual behaviour:

Line is formatted with spaces instead of tabs for the leading whitespace.

_Copied from original issue: Microsoft/vscode#14108_

### PR DESCRIPTION
**Pull request by filipw**
This should fix #834 and related issues.

This PR ensures that we pass VS Code `editor.*` settings related to tabs/indentation into OmniSharp (through environment variables, which OmniSharp already supports - no changes needed there). This way, when invoking commands such as `Format Document`, we will respect the user set up in his VS Code, rather than imposing OmniSharp defaults (spaces over tabs, 4 spaces indentation).

This feature can be opt out from by setting `omnisharp.useEditorFormattingSettings` to `false`.

Additionally, OmniSharp has its own tab vs spaces and indentation rules that can be controlled using `omnisharp.json`. If this file is present in the current working directory, it will still take precedence as it was in the past - no change there.

### CODE REVIEW

File: src/omnisharp/launcher.ts [hunk 1]
```diff
@@ -193,6 +202,7 @@ function launchWindows(launchPath: string, cwd: string, args: string[]): LaunchR
     }
 
     let argsCopy = args.slice(0); // create copy of args
+    //argsCopy.push('--debug');
```
Comment (DustinCampbell) [inline src/omnisharp/launcher.ts]: Why is this added and commented out?

File: src/omnisharp/launcher.ts [hunk 2]
```diff
@@ -161,17 +161,26 @@ function launch(cwd: string, args: string[]): Promise<LaunchResult> {
...
         const options = Options.Read();
 
+        let envVars = {};
+        if (options.useEditorFormattingSettings) 
+        {
+            let editorConfig = vscode.workspace.getConfiguration('editor');
+            envVars['formattingOptions:useTabs'] = !editorConfig.get('insertSpaces', true);
+            envVars['formattingOptions:tabSize'] = editorConfig.get('tabSize', 4);
+            envVars['formattingOptions:indentationSize'] = editorConfig.get('tabSize', 4);
+        }
```
Comment (DustinCampbell) [inline src/omnisharp/launcher.ts]: Can't these just be passed as additional arguments? I though OmniSharp's configuration builder would pick these up from the command line.

**Comment by DustinCampbell** [comment]
This will also address https://github.com/OmniSharp/omnisharp-vscode/issues/93.

File: src/omnisharp/launcher.ts (hunk 1 above)
Comment (filipw) [inline src/omnisharp/launcher.ts]: oops my dirty attaching of a debugger 😞

File: src/omnisharp/launcher.ts (hunk 2 above)
Comment (filipw) [inline src/omnisharp/launcher.ts]: yes they can - in fact I believe `restore packages` is passed like that already if I recall correctly. I can change that for consistency, there is no real reason to use environment variables indeed

Comment (DustinCampbell) [inline src/omnisharp/launcher.ts]: That's what I thought -- thanks! Yeah, go ahead and pass them as args for consistency. I have no idea what the logic is for options overriding in the configuration middleware that OmniSharp uses. E.g. do command line args override environment variable or vice versa? I just ran into something similar with MSBuild, so it was on my mind. Hence, the question. :smile:

**Comment by filipw** [comment]
Updated the PR to pass the formatting options using command line instead of env vars. 

OmniSharp now starts like this, with your editor settings passed in: 

`OmniSharp: -s c:\code\csharp-scripting-demos\dotnetcli-and-debug --hostPID 3408 --stdio DotNet:enablePackageRestore=false --encoding utf-8 -v formattingOptions:useTabs=true formattingOptions:tabSize=2 formattingOptions:indentationSize=2`

If you opt out of the formatting settings sharing, then it will start same as before i.e.: 

`OmniSharp: -s c:\code\csharp-scripting-demos\dotnetcli-and-debug --hostPID 4024 --stdio DotNet:enablePackageRestore=false --encoding utf-8 -v`

**Comment by filipw** [comment]
I also created a wiki page https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration%20Options - might be useful if folks have questions in the future

**Comment by filipw** [comment]
thanks!
